# Generated by Django 2.1.5 on 2019-04-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('status', models.CharField(default='idle', max_length=30)),
                ('txt_ind', models.BooleanField(default=False)),
                ('img_ind', models.BooleanField(default=False)),
                ('txt_slug', models.CharField(blank=True, max_length=100)),
                ('img_slug', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
